springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/
spring.data.redis.host=localhost

spring.data.redis.port=6379
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asktest281@gmail.com
spring.mail.password=xtsw vujm ouws frdw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
#//
logging.level.root=INFO