db.jdbcUrl=jdbc:postgresql://80.238.227.209:9356/asklepios
db.user=asklepios
db.password=qqV9pb08@EM2r!
spring.datasource.driver-class-name=org.postgresql.Driver
#db.jdbcUrl=jdbc:postgresql://localhost:5432/asklepios
#db.user=postgres
#db.password=Pass@123


