jdbcUrl=jdbc:postgresql://db-postgresql-nyc3-94186-do-user-10936078-0.j.db.ondigitalocean.com:25060/asklepios
dataSource.user=asklepios
dataSource.password=AVNS_Dw0mJXT6mnivz3bN70_
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
dataSource.poolName=Asklepios Datasource
dataSource.minimumIdle=3
dataSource.maximumPoolSize=10

#jdbcUrl=jdbc:postgresql://164.68.96.9/asklepios
#dataSource.user=asklepios_remote
#dataSource.password=Bane@4994
#dataSource.cachePrepStmts=true
#dataSource.prepStmtCacheSize=250
#dataSource.prepStmtCacheSqlLimit=2048
#dataSource.poolName=Asklepios Datasource
#dataSource.minimumIdle=3
#dataSource.maximumPoolSize=10




#jdbcUrl=jdbc:postgresql://localhost/asklepios
#dataSource.user=postgres
#dataSource.password=Pass@123
#dataSource.cachePrepStmts=true
#dataSource.prepStmtCacheSize=250
#dataSource.prepStmtCacheSqlLimit=2048
#dataSource.poolName=Asklepios Datasource
#dataSource.minimumIdle=3
#dataSource.maximumPoolSize=10