db.jdbcUrl=jdbc:postgresql://161.35.195.29:5432/asklepios
db.user=asklepios
db.password=AVNS_Dw0mJXT6mnivz3bN70_
spring.datasource.driver-class-name=org.postgresql.Driver
#db.jdbcUrl=jdbc:postgresql://localhost:5432/asklepios
#db.user=postgres
#db.password=Pass@123


