---
# Service
apiVersion: v1
kind: Service
metadata:
    name: asklepiosdemo-service
    namespace: asklepios-sandbox
spec:
    type: ClusterIP
    selector:
        app: asklepiosdemo-service
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8080
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: asklepiosdemo-service
    namespace: asklepios-sandbox
spec:
    selector:
        matchLabels:
            app: asklepiosdemo-service
    replicas: 1
    template:
        metadata:
            labels:
                app: asklepiosdemo-service
        spec:
            containers:
                - name: asklepiosdemo-service
                  image: registry.digitalocean.com/asklepios/asklepios-api-service:demo.532a77f6a67418822971a8a66bf9c15f65871f00
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                        name: askp-service
            imagePullSecrets:
                - name: asklepios

