package com.asklepios.backend_service.model.DTO;

import java.util.ArrayList;
import java.util.List;

public class PatientSummaryDTO {

    // Age as FREE TEXT
    private String age;

    private String gender;
    private String diagnosis;          // Major diagnosis as single string

    // Observation + chief complaint + pain + additional
    private String symptoms;

    // Lists
    private List<String> medications = new ArrayList<>();
    private List<String> surgeries = new ArrayList<>();
    private List<String> allergies = new ArrayList<>();

    // Warnings as single string (type + warning)
    private String medicalWarnings;

    // Problems
    private List<String> problems = new ArrayList<>();

    // Vitals FREE TEXT
    private String vitals;

    // Clinical summary generated by AI
    private String clinicalSummary;

    // ===== getters & setters =====

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getDiagnosis() {
        return diagnosis;
    }

    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }

    public String getSymptoms() {
        return symptoms;
    }

    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }

    public List<String> getMedications() {
        return medications;
    }

    public void setMedications(List<String> medications) {
        this.medications = medications;
    }

    public List<String> getSurgeries() {
        return surgeries;
    }

    public void setSurgeries(List<String> surgeries) {
        this.surgeries = surgeries;
    }

    public List<String> getAllergies() {
        return allergies;
    }

    public void setAllergies(List<String> allergies) {
        this.allergies = allergies;
    }

    public String getMedicalWarnings() {
        return medicalWarnings;
    }

    public void setMedicalWarnings(String medicalWarnings) {
        this.medicalWarnings = medicalWarnings;
    }

    public List<String> getProblems() {
        return problems;
    }

    public void setProblems(List<String> problems) {
        this.problems = problems;
    }

    public String getVitals() {
        return vitals;
    }

    public void setVitals(String vitals) {
        this.vitals = vitals;
    }

    public String getClinicalSummary() {
        return clinicalSummary;
    }

    public void setClinicalSummary(String clinicalSummary) {
        this.clinicalSummary = clinicalSummary;
    }
}